# Generated by Django 5.2.14 on 2026-05-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimbingProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("grade", models.CharField(max_length=40)),
                (
                    "grade_system",
                    models.CharField(
                        choices=[
                            ("v_scale", "V-scale"),
                            ("yds", "YDS"),
                            ("font", "Font"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bouldering", "Bouldering"),
                            ("top_rope", "Top rope"),
                            ("sport", "Sport"),
                            ("trad", "Trad"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateField(blank=True, null=True)),
                ("sent_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climbing_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["status", "name"],},
        ),
        migrations.CreateModel(
            name="ClimbingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=180)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("bouldering", "Bouldering"),
                            ("top_rope", "Top rope"),
                            ("sport", "Sport"),
                            ("trad", "Trad"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climbing_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-date", "-created_at"],},
        ),
        migrations.CreateModel(
            name="ClimbAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("climb_name", models.CharField(blank=True, max_length=180)),
                (
                    "grade_system",
                    models.CharField(
                        choices=[
                            ("v_scale", "V-scale"),
                            ("yds", "YDS"),
                            ("font", "Font"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("grade", models.CharField(max_length=40)),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slab", "Slab"),
                            ("vertical", "Vertical"),
                            ("overhang", "Overhang"),
                            ("roof", "Roof"),
                            ("crimpy", "Crimpy"),
                            ("sloper", "Sloper"),
                            ("pinch", "Pinch"),
                            ("dyno", "Dyno"),
                            ("technical", "Technical"),
                            ("powerful", "Powerful"),
                            ("endurance", "Endurance"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("flash", "Flash"),
                            ("send", "Send"),
                            ("repeat", "Repeat"),
                            ("project", "Project"),
                            ("fail", "Fail"),
                            ("attempt", "Attempt"),
                            ("clean", "Clean"),
                            ("take", "Take"),
                            ("fall", "Fall"),
                            ("complete", "Complete"),
                        ],
                        max_length=24,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="climbing.climbingsession",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "id"],},
        ),
    ]
