# Generated by Django 5.2.14 on 2026-05-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climbing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="climbattempt",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="climbing.climbingproject",
            ),
        ),
    ]
