# Generated by Django 5.2.14 on 2026-05-05 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("started_at", models.DateTimeField()),
                ("distance_km", models.FloatField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("avg_pace_seconds_per_km", models.FloatField(blank=True, null=True)),
                ("avg_hr", models.FloatField(blank=True, null=True)),
                ("max_hr", models.FloatField(blank=True, null=True)),
                ("elevation_gain_m", models.FloatField(blank=True, null=True)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("long_run", "Long run"),
                            ("tempo", "Tempo"),
                            ("interval", "Interval"),
                            ("recovery", "Recovery"),
                            ("race", "Race"),
                            ("hill", "Hill"),
                            ("progression", "Progression"),
                            ("other", "Other"),
                        ],
                        default="easy",
                        max_length=24,
                    ),
                ),
                (
                    "perceived_effort",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("source", models.CharField(default="manual", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-started_at", "-created_at"],},
        ),
    ]
