# Generated by Django 5.2.14 on 2026-05-06 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="runactivity",
            name="raw_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="runactivity",
            name="source_activity_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("garmin_export", "Garmin export"),
                            ("strava_export", "Strava export"),
                            ("manual_upload", "Manual upload"),
                            ("other", "Other"),
                        ],
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("tcx", "TCX"),
                            ("gpx", "GPX"),
                            ("fit", "FIT"),
                            ("csv", "CSV"),
                            ("zip", "ZIP"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(upload_to="imports/running/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "import batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="runactivity",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="running.importbatch",
            ),
        ),
    ]
