# Generated by Django 5.2.14 on 2026-05-05 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "movement_pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("push", "Push"),
                            ("pull", "Pull"),
                            ("squat", "Squat"),
                            ("hinge", "Hinge"),
                            ("lunge", "Lunge"),
                            ("carry", "Carry"),
                            ("rotation", "Rotation"),
                            ("isolation", "Isolation"),
                            ("core", "Core"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("barbell", "Barbell"),
                            ("dumbbell", "Dumbbell"),
                            ("machine", "Machine"),
                            ("cable", "Cable"),
                            ("bodyweight", "Bodyweight"),
                            ("kettlebell", "Kettlebell"),
                            ("band", "Band"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("form_notes", models.TextField(blank=True)),
                ("is_custom", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_muscle_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_exercises",
                        to="gym.musclegroup",
                    ),
                ),
                (
                    "secondary_muscle_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_exercises",
                        to="gym.musclegroup",
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="ExerciseReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=180)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="gym.exercise",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="GymSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "split_type",
                    models.CharField(
                        choices=[
                            ("push", "Push"),
                            ("pull", "Pull"),
                            ("legs", "Legs"),
                            ("upper", "Upper"),
                            ("lower", "Lower"),
                            ("full_body", "Full body"),
                            ("custom", "Custom"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-date", "-created_at"],},
        ),
        migrations.CreateModel(
            name="GymSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveIntegerField()),
                ("weight", models.FloatField(blank=True, null=True)),
                ("reps", models.PositiveIntegerField()),
                (
                    "rpe",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=220)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gym_sets",
                        to="gym.exercise",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="gym.gymsession",
                    ),
                ),
            ],
            options={"ordering": ["set_number", "id"],},
        ),
    ]
