# Generated by Django 5.2.14 on 2026-05-08 04:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0004_exercise_archive_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "split_type",
                    models.CharField(
                        choices=[
                            ("push", "Push"),
                            ("pull", "Pull"),
                            ("legs", "Legs"),
                            ("upper", "Upper"),
                            ("lower", "Lower"),
                            ("full_body", "Full body"),
                            ("custom", "Custom"),
                        ],
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["is_archived", "split_type", "name"],},
        ),
        migrations.CreateModel(
            name="ActiveWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("current_exercise_index", models.PositiveIntegerField(default=0)),
                ("current_set_index", models.PositiveIntegerField(default=0)),
                ("logged_sets", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_workout",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_workouts",
                        to="gym.workouttemplate",
                    ),
                ),
            ],
            options={"ordering": ["-started_at"],},
        ),
        migrations.CreateModel(
            name="WorkoutTemplateExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("target_sets", models.PositiveIntegerField(default=3)),
                ("target_reps_low", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_reps_high",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("suggested_weight", models.FloatField(blank=True, null=True)),
                ("rest_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_items",
                        to="gym.exercise",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gym.workouttemplate",
                    ),
                ),
            ],
            options={"ordering": ["order", "id"],},
        ),
    ]
