# Generated by Django 5.2.14 on 2026-05-27 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_focus",
                    models.CharField(
                        choices=[
                            ("balanced", "Balanced"),
                            ("running", "Running"),
                            ("gym", "Gym"),
                            ("climbing", "Climbing"),
                        ],
                        default="balanced",
                        max_length=16,
                    ),
                ),
                (
                    "running_goal",
                    models.CharField(
                        choices=[
                            ("general_fitness", "General fitness"),
                            ("5k", "5K"),
                            ("10k", "10K"),
                            ("half_marathon", "Half marathon"),
                            ("marathon", "Marathon"),
                        ],
                        default="general_fitness",
                        max_length=32,
                    ),
                ),
                (
                    "running_sessions_per_week",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "running_weekly_distance_target_km",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gym_goal",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("hypertrophy", "Hypertrophy"),
                            ("general_fitness", "General fitness"),
                            ("climbing_support", "Climbing support"),
                        ],
                        default="general_fitness",
                        max_length=32,
                    ),
                ),
                (
                    "gym_sessions_per_week",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "climbing_goal",
                    models.CharField(
                        choices=[
                            ("bouldering", "Bouldering"),
                            ("top_rope", "Top rope"),
                            ("mixed", "Mixed"),
                            ("general_progression", "General progression"),
                        ],
                        default="general_progression",
                        max_length=32,
                    ),
                ),
                (
                    "climbing_sessions_per_week",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "climbing_target_bouldering_grade",
                    models.CharField(default="V4", max_length=16),
                ),
                (
                    "climbing_target_route_grade",
                    models.CharField(default="5.10a", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "training preferences",},
        ),
    ]
